---
- hosts: localhost
  gather_facts: true
  collections:
    - hpe.oneview
  
  tasks:
    - name: Add a Server Hardware
      hpe.oneview.oneview_server_hardware:
        hostname: "{{ oneview_hostname }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        state: present
        data:
          hostname : "172.16.15.216"
          username : "Administrator"
          password : "Pa$$w0rd"
          force : false
          licensingIntent: "OneView"
          configurationState: "Managed"
      delegate_to: localhost

