---
- hosts: esx_hosts
  gather_facts: false
  collections:
    - hpe.oneview
  
  tasks:
    - name: Add a Server Hardware
      hpe.oneview.oneview_server_hardware:
        hostname: "{{ oneview_hostname }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        state: present
        data:
          hostname : "{{ilo_ip}}"
          username : "admin"
          password : "{{ilo_pw}}"
          force : false
          licensingIntent: "OneView"
          configurationState: "Managed"
      delegate_to: localhost

    - name: Gather facts about all Server Hardwares
      hpe.oneview.oneview_server_hardware_facts:
        hostname: "{{ oneview_hostname }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
      delegate_to: localhost

    
