---
- hosts: esx_hosts
  gather_facts: no

  tasks:
    - name: Gather facts about all Server Profiles
      hpe.oneview.oneview_server_profile_facts:
        hostname: "{{ hostvars.oneview_host.ansible_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
      delegate_to: localhost