---
- hosts: esx_hosts
  gather_facts: false
  collections:
    - hpe.oneview
  
  tasks:
    - name: Add a Server Hardware
      hpe.oneview.oneview_server_hardware:
        hostname: "{{ oneview_hostname }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        state: absent
        data:
          name: "{{ilo_dns}}"
          
      delegate_to: localhost
      ignore_errors: true

 
   

    
