---
- hosts: esx_hosts
  gather_facts: no

  vars:
    # ov_hardwarename is ilo_dns name
    ov_hardware: "{{ilo_dns}}"
  
  # Import ServerProfile from KD-vars
  vars_files:
    - "{{kd_server_profile}}"

  tasks:
    - fail:
        msg: "You need to define ov_hardware for each host which should be deployed via this script"
      when: ov_hardware is undefined 

    - name: Power Off compute in order to deploy the profile
      hpe.oneview.oneview_server_hardware:
        hostname: "{{ hostvars.oneview_host.ansible_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        state: power_state_set
        data:
          name : '{{ ov_hardware }}'
          powerStateData:
            powerState: "Off"
            powerControl: "PressAndHold"
      delegate_to: localhost
    
    - name: Create profile and assign to server
      hpe.oneview.oneview_server_profile:
        hostname: "{{ hostvars.oneview_host.ansible_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        data:
          "{{server_profile_data}}"
        params:
          force: True
      delegate_to: localhost

    - name: Gather sso iLO url facts about a Server Hardware
      hpe.oneview.oneview_server_hardware_facts:
        hostname: "{{ hostvars.oneview_host.ansible_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        name: "{{ ov_hardware }}"
        options:
          - remoteConsoleUrl
      delegate_to: localhost
 
    - name: Power Off the server hardware
      hpe.oneview.oneview_server_hardware:
        hostname: "{{ hostvars.oneview_host.ansible_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        state: power_state_set
        data:
            name : '{{ ov_hardware }}'
            powerStateData:
                powerState: "Off"
                powerControl: "PressAndHold"
      delegate_to: localhost