---
- hosts: esx_hosts
  gather_facts: no

  vars:

  tasks:
    - fail:
        msg: "You need to define ov_hardware for each host which should be deployed via this script"
      when: ov_hardware is undefined 

    - name: Set Oneview Server Profile Name for the host in question
      set_fact:
        ov_profile: "BechtlePower_{{ inventory_hostname_short }}"
      when: ov_profile is undefined or ov_profile is not match ("^Workshop_.*")

    - name: Power Off compute in order to remove the profile
      hpe.oneview.oneview_server_hardware:
        hostname: "{{ hostvars.oneview_host.ansible_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        state: power_state_set
        data:
          name : '{{ ov_hardware }}'
          powerStateData:
            powerState: "Off"
            powerControl: "PressAndHold"
      delegate_to: localhost
    
    - name: Create profile and assign to server
      hpe.oneview.oneview_server_profile:
        hostname: "{{ hostvars.oneview_host.ansible_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        data:
          name: "{{ ov_profile }}"
          serverHardwareName: "{{ ov_hardware }}"
          bios:
            manageBios: true
            reapplyState: NotApplying
            consistencyState: Consistent
            overriddenSettings:
              - id: WorkloadProfile
                value: Virtualization-MaxPerformance
              - id: PowerRegulator
                value: StaticHighPerf
              - id: MinProcIdlePower
                value: NoCStates
              - id: MinProcIdlePkgState
                value: NoState
              - id: EnergyPerfBias
                value: MaxPerf
              - id: CollabPowerControl
                value: Disabled
              - id: NumaGroupSizeOpt
                value: Clustered
              - id: UncoreFreqScaling
                value: Maximum
              - id: SubNumaClustering
                value: Enabled
              - id: EnergyEfficientTurbo
                value: Disabled
              - id: IntelUpiPowerManagement
                value: Disabled
          boot:
            order:
              - CD
              - USB
              - HardDisk
              - PXE
            manageBoot: true
          bootMode:
            mode: BIOS
            manageMode: true
            secureBoot: Disabled
            pxeBootPolicy: null
          localStorage:
            controllers:
              - mode: Mixed
                deviceSlot: Embedded
                initialize: false
                logicalDrives:
                  - name: OsVol666
                    bootable: true
                    raidLevel: RAID1
                    accelerator: Unmanaged
                    driveNumber: 1
                    numSpareDrives: null
                    driveTechnology: SasHdd
                    sasLogicalJBODId: null
                    numPhysicalDrives: 2
                driveWriteCache: Unmanaged
                importConfiguration: false
                predictiveSpareRebuild: Unmanaged
            reapplyState: NotApplying
            sasLogicalJBODs: []
          managementProcessor:
            manageMp: true
            mpSettings:
              - args:
                  localAccounts:
                    - password: {{ilo_pw}}
                      userName: admin
                      loginPriv: true
                      displayName: admin
                      iLOConfigPriv: true
                      userConfigPriv: true
                      virtualMediaPriv: true
                      hostNICConfigPriv: true
                      remoteConsolePriv: true
                      hostBIOSConfigPriv: true
                      hostStorageConfigPriv: true
                      virtualPowerAndResetPriv: true
                settingType: LocalAccounts
            reapplyState: NotApplying
        params:
          force: True
      delegate_to: localhost

    - name: Ensure profile state is compliant
      hpe.oneview.oneview_server_profile:
        hostname: "{{ hostvars.oneview_host.ansible_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        state: "compliant"
        data:
          name: "{{ ov_profile }}"
      delegate_to: localhost

    - name: Gather sso iLO url facts about a Server Hardware
      hpe.oneview.oneview_server_hardware_facts:
        hostname: "{{ hostvars.oneview_host.ansible_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        name: "{{ ov_hardware }}"
        options:
          - remoteConsoleUrl
      delegate_to: localhost
 
    - name: Power Off the server hardware
      hpe.oneview.oneview_server_hardware:
        hostname: "{{ hostvars.oneview_host.ansible_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        state: power_state_set
        data:
            name : '{{ ov_hardware }}'
            powerStateData:
                powerState: "Off"
                powerControl: "PressAndHold"
      delegate_to: localhost