---
- hosts: esx_hosts
  gather_facts: false
  collections:
    - hpe.oneview
  
  tasks:
    - name: Power of Server gentley
      hpe.oneview.oneview_server_hardware:
        hostname: "{{ oneview_hostname }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        state: power_state_set
        data:
          name : "{{ilo_dns}}"
          powerStateData:
            powerState: "Off"
            powerControl: "MomentaryPress"
      delegate_to: localhost
      
    - name: Remove a Server Profile
      hpe.oneview.oneview_server_profile:
        hostname: "{{ oneview_hostname }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        state: absent
        data:
          name: "{{ov_profile}}"
      delegate_to: localhost

    - name: Remove a Server Hardware
      hpe.oneview.oneview_server_hardware:
        hostname: "{{ oneview_hostname }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        state: absent
        data:
          name: "{{ilo_dns}}"
      delegate_to: localhost
    
    - name: "set completed fact deploy_status"
      set_fact:
        deploy_status: completed
        cacheable: true

 
   

    
