---
- hosts: esx_hosts
  gather_facts: no
  become: false

  tasks:
  - name: debug hostvars
    debug:
      var: hostvars

  - name: debug bastion_host ipaddress
    debug:
      var: hostvars.bastion_host.ansible_host
  - name: debug esxi inventory ip address
    debug:
      var: ansible_default_ipv4.address

  - name: "set begin install fact deploy_status"
    set_fact:
      deploy_status: install_os
      cacheable: true

  - name: Task to boot a system using an ISO from an HP iLO interface to install esxi
    community.general.hpilo_boot:
      host: "{{ ilo_ip }}" 
      login: "{{ ilo_user }}"
      password: "{{ ilo_pw }}"
      media: cdrom
      image: "{{ esxi_installiso }}" 
    delegate_to: localhost

  - name: waiting for esx host to come online
    wait_for:
      port: 80
      host: "{{ esxi_ip }}"
      delay: 1
      timeout: 900
    connection: local