---
- hosts: esx_hosts
  gather_facts: no
  ##  become: true

  tasks:

   - name: Unmount installation ISO 
     mount:
       path: "{{ mnt_dir }}"
       state: unmounted
     become: true
     delegate_to: bastion_host

   - name: Remove workingdir with Iso content
     file:
       path: "{{ item }}"
       state: absent
     become: true
     loop:
        - "{{ wrk_dir }}"
        - "{{ mnt_dir }}"
      delegate_to: bastion_host
     # needs to run as root as file ownership will not allow deletion otherwise 

   - name: Remove customized iso image
     file:
       path: "{{ cust_iso }}"
       state: absent
     become: true
     delegate_to: bastion_host
     # needs to run as root as file ownership will not allow deletion otherwise 

