---
# Oneview configuration
ov_profile: "{{kd_name}}_{{ inventory_hostname_short }}"
server_hardware_type_name: "DL 380 Gen10 1"

# VMware Install related vars
cust_iso_file: "{{ ov_profile }}_esxi.iso"
bastion_get_url: "http://{{ hostvars.bastion_host.ansible_host }}/iso"
bastion_iso_dir: /var/www/html/iso
esxi_installiso: "{{ bastion_get_url }}/{{ cust_iso_file }}"

# adjustable VMware installation related vars:
cust_iso: "{{ bastion_iso_dir }}/{{ cust_iso_file }}"

# fixed WMware installation related vars:
ks_template: ks.cfg
mnt_dir:  /esxi_cdrom_mount
wrk_dir:  /esxi_cdrom
ks_dest: "{{ wrk_dir }}/ks.cfg"
bootoption: "runweasel ks=cdrom:/KS.CFG"
bootcfg_dest: "{{ wrk_dir }}/efi/boot/boot.cfg"
bootcfg_dest2: "{{ wrk_dir }}/boot.cfg"

